
on:
 workflow_dispatch:

jobs:
  archbuild:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: build
      run: |
        f=/bin/makepkg
        e="catastrophic damage"
        grep "^$e" -n $f -B 1 -A 1
        n=`grep "^$e" -n $f | grep -o "^[^:]*"`
        n=$((n+1))
        sed -i "${n}s/.*//" $f
        name=`cat debian/changelog | head -1 | grep -o ^[^\ ]*`
        pacman -Sy --noconfirm --needed git base-devel
        git clone -n --depth=1 --filter=tree:0 https://github.com/colin-i/pkgbuilds
        #--filter in git-rev-list
        cd pkgbuilds
        git sparse-checkout set --no-cone /${name}
        git checkout
        cd ${name}
        makepkg -s --noconfirm
        ls
        nm=`ls | grep ".*\.zst$" | grep -v debug`
        nm2=`echo ${nm} | sed s/-any/-arch-x86_64/`
        mv ${nm} ../../${nm2}
        echo "file=${nm2}" >> $GITHUB_ENV
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: pkg
        path: ./${{ env.file }}
